services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    ports:
      - "8765:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - andy-angular-template-volume:/opt/keycloak/data
    command: start-dev
    networks:
      - andy-angular-template-network
    restart: always

networks:
  andy-angular-template-network:
    driver: bridge
volumes:
  andy-angular-template-volume:
    driver: local
